export const LIMITS = {
  CATEGORIES_LIMITS: 18,
  PRODUCTS_LIMITS: 10,
  REFINED_PRODUCTS_LIMITS: 20,
  RELATED_PRODUCTS_LIMITS: 15,
  BEST_SELLER_PRODUCTS_LIMITS: 15,
  POPULAR_PRODUCTS_LIMITS: 14,
  POPULAR_PRODUCTS_TWO_LIMITS: 10,
};
